name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            output: linux
          - os: windows-latest
            output: windows
          - os: macos-latest
            output: darwin

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        env:
          GOOS: ${{ matrix.output }}
          GOARCH: amd64
        run: |
          go build -v -o dist/dnstools-${{ matrix.output }}-amd64 -ldflags="-s -w" ./cmd/dnstool

      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          generate_release_notes: true